"""Color palette and semantic tokens."""

# --- Palette (what the colors ARE) ---
CREAM = "#F5F0E8"
SAGE = "#4EBA65"
CHARCOAL = "#373737"
LAVENDER = "#B1B9F9"
EMBER = "#E07A47"
SLATE = "#555555"
STONE = "#888888"
PEBBLE = "#aaaaaa"
MINT = "#86E89A"
CORAL = "#FF7A7A"
SKY = "#7AB8FF"
PLUM = "#3B3154"

# --- Semantic tokens (what the colors MEAN) ---
COLOR_MUTED = STONE
COLOR_MUTED_LIGHT = PEBBLE
COLOR_STAGED = SAGE
COLOR_CURSOR_BG = f"on {CHARCOAL}"
COLOR_RANGE_BG = f"on {CHARCOAL}"
COLOR_ACCENT = LAVENDER
COLOR_INACTIVE = SLATE
COLOR_DIFF = EMBER
COLOR_ADDITION = MINT
COLOR_WARNING = CORAL
COLOR_LINK = SKY
COLOR_COLUMN_FOCUS_BG = f"on {PLUM}"
